root: true

extends:
  - '@form8ion'
  - '@form8ion/vitest'
  - '@form8ion/cucumber'

parserOptions:
  ecmaVersion: 2022

overrides:
  - files: "src/index.js"
    rules:
      "import/no-unresolved":
        - error
        - ignore:
            - "yargs/helpers"

rules:
  import/extensions:
    - error
    - ignorePackages
