name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - 'renovate/**'
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm clean-install
      - run: npm test
      - name: Upload coverage data to Codecov
        run: 'npm run coverage:report'
  trigger-release:
    needs: verify
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/dispatches
          owner: form8ion
          repo: utils-cli
          event_type: release,
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
